dailyfresh/apps/cart/urls.py
from django.urls import path
from cart.views import CartAddView, CartInfoView, CartUpdateView, CartDeleteView

urlpatterns = [
    path('add', CartAddView.as_view(), name='add'),
    path('', CartInfoView.as_view(), name='show'),
    path('update', CartUpdateView.as_view(), name='update'),
    path('delete', CartDeleteView.as_view(), name='delete')
]

dailyfresh/apps/goods/urls.py
from django.contrib import admin
from django.urls import path, include
from goods.views import IndexView, DetailView, ListView

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('goods/<int:goods_id>', DetailView.as_view(), name='detail'),
    path('list/<int:type_id>/<int:page>/', ListView.as_view(), name='list')
]

dailyfresh/apps/user/urls.py
from django.contrib import admin
from django.urls import path, include
from user.views import RegisterView, ActiveView, LoginView, UserInfoView, UserOrderView, AddressView, LogoutView

urlpatterns = [
    path('register', RegisterView.as_view(), name='register'),  # 注册
    path('activate/<str:token>', ActiveView.as_view(), name='active'),  # 激活
    path('login', LoginView.as_view(), name='login'),  # 登录
    path('logout', LogoutView.as_view(), name='logout'),
    path('', UserInfoView.as_view(), name='center'),
    path('order/<int:page>/', UserOrderView.as_view(), name='order'),
    path('address', AddressView.as_view(), name='address')
]

dailyfresh/dailyfresh/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('search',include('haystack.urls')),
    path('tinymce/', include('tinymce.urls')),  # 富文本编辑器
    path('user/', include(('user.urls', 'user'), namespace='user')),
    path('cart/', include(('cart.urls', 'cart'), namespace='cart')),
    path('order/', include(('order.urls', 'order'), namespace='order')),
    path('', include(('goods.urls', 'goods'), namespace='goods'))
]

dailyfresh/demo/urls.py
from django.contrib import admin
from django.urls import path, re_path
from api import views
from demo.settings import MEDIA_ROOT
from django.views.static import serve
from django.conf import settings
from django.conf.urls.static import static
from api.views import IndexView,LineView,BarView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(),name='index'),
    path('api/line', LineView.as_view(),name='line'),
    path('api/bar', BarView.as_view(),name='bar'),
    path('api/wx_login', views.wx_login),
    path('api/get_employees', views.get_employees),
    path('api/get_employee_by_id', views.get_employee_by_id),
    path('api/get_comment_by_openId', views.get_comment_by_openId),
    path('api/add_comment', views.add_comment),
    # path('media/(<str:path>.*)', serve, {"document_root": MEDIA_ROOT})
    re_path(r'^media/(?P<path>.*)$', serve, {"document_root": MEDIA_ROOT})
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

dailyfresh/apps/cart/models.py
from django.db import models

# Create your models here.

dailyfresh/apps/goods/models.py
from django.db import models
from db.base_model import BaseModel
from tinymce.models import HTMLField
# Create your models here.


class GoodsType(BaseModel):
    '''商品类型模型类'''

    name = models.CharField(max_length=20, verbose_name='种类名称')
    logo = models.CharField(max_length=20, verbose_name='标识')
    image = models.ImageField(upload_to='type', verbose_name='商品类型图片')

    class Meta:
        db_table = 'df_goods_type'
        verbose_name = '分类'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class GoodsSKU(BaseModel):
    '''商品SKU模型类'''
    status_choices = (
        (0, '下线'),
        (1, '上线'),
    )
    type = models.ForeignKey(
        'GoodsType', verbose_name='分类', on_delete=models.CASCADE)
    goods = models.ForeignKey(
        'Goods', verbose_name='商品SPU', on_delete=models.CASCADE)
    name = models.CharField(max_length=20, verbose_name='商品名称')
    desc = models.CharField(max_length=256, verbose_name='商品简介')
    price = models.DecimalField(
        max_digits=10, decimal_places=2, verbose_name='商品价格')
    unite = models.CharField(max_length=20, verbose_name='商品单位')
    image = models.ImageField(upload_to='goods', verbose_name='商品图片')
    stock = models.IntegerField(default=1, verbose_name='商品库存')
    sales = models.IntegerField(default=0, verbose_name='商品销量')
    status = models.SmallIntegerField(
        default=1, choices=status_choices, verbose_name='商品状态')

    class Meta:
        db_table = 'df_goods_sku'
        verbose_name = '商品'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class Goods(BaseModel):
    '''商品SPU模型类'''
    name = models.CharField(max_length=20, verbose_name='商品SPU名称')
    # 富文本类型:带有格式的文本
    detail = HTMLField(blank=True, verbose_name='商品详情')

    class Meta:
        db_table = 'df_goods'
        verbose_name = '商品SPU'
        verbose_name_plural = verbose_name
    
    def __str__(self):
        return self.name


class GoodsImage(BaseModel):
    '''商品图片模型类'''
    sku = models.ForeignKey(
        'GoodsSKU', verbose_name='商品', on_delete=models.CASCADE)
    image = models.ImageField(upload_to='goods', verbose_name='图片路径')

    class Meta:
        db_table = 'df_goods_image'
        verbose_name = '商品图片'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.sku.name


class IndexGoodsBanner(BaseModel):
    '''首页轮播商品展示模型类'''
    sku = models.ForeignKey(
        'GoodsSKU', verbose_name='商品', on_delete=models.CASCADE)
    image = models.ImageField(upload_to='banner', verbose_name='图片')
    index = models.SmallIntegerField(default=0, verbose_name='展示顺序')

    class Meta:
        db_table = 'df_index_banner'
        verbose_name = '轮播广告'
        verbose_name_plural = verbose_name
    
    def __str__(self):
        return self.sku.name


class IndexTypeGoodsBanner(BaseModel):
    '''首页分类商品展示模型类'''
    DISPLAY_TYPE_CHOICES = (
        (0, "标题"),
        (1, "图片")
    )

    type = models.ForeignKey(
        'GoodsType', verbose_name='商品类型', on_delete=models.CASCADE)
    sku = models.ForeignKey(
        'GoodsSKU', verbose_name='商品SKU', on_delete=models.CASCADE)
    display_type = models.SmallIntegerField(
        default=1, choices=DISPLAY_TYPE_CHOICES, verbose_name='展示类型')
    index = models.SmallIntegerField(default=0, verbose_name='展示顺序')

    class Meta:
        db_table = 'df_index_type_goods'
        verbose_name = "分类展示商品"
        verbose_name_plural = verbose_name
    
    def __str__(self):
        return self.sku.name


class IndexPromotionBanner(BaseModel):
    '''首页促销活动模型类'''
    name = models.CharField(max_length=20, verbose_name='活动名称')
    url = models.URLField(verbose_name='活动链接')
    image = models.ImageField(upload_to='banner', verbose_name='活动图片')
    index = models.SmallIntegerField(default=0, verbose_name='展示顺序')

    class Meta:
        db_table = 'df_index_promotion'
        verbose_name = "促销活动"
        verbose_name_plural = "主页促销活动"
    
    def __str__(self):
        return self.name

dailyfresh/apps/cart/views.py
from django.shortcuts import render
from django.views.generic import View
from django.http import JsonResponse
from goods.models import GoodsSKU
from django_redis import get_redis_connection
from utils.mixin import LoginRequiredMixin
# Create your views here.


class CartAddView(View):
    def post(self, request):
        sku_id = request.POST.get('sku_id')
        count = request.POST.get('count')
        user = request.user
        if not user.is_authenticated:
            return JsonResponse({'res': 4, 'error': '请登录'})

        if not all([sku_id, count]):
            return JsonResponse({'res': 0, 'error': '数据不完整'})

        try:
            count = int(count)
        except Exception as e:
            return JsonResponse({'res': 1, 'error': '商品数量出错'})

        try:
            sku = GoodsSKU.objects.get(id=sku_id)
        except GoodsSKU.DoesNotExist:
            return JsonResponse({'res': 2, 'error': '商品不存在'})

        conn = get_redis_connection('default')
        cart_key = 'cart_%d' % user.id
        cart_count = conn.hget(cart_key, sku_id)

        if cart_count:
            count += int(cart_count)
        if count > sku.stock:
            return JsonResponse({'res': 3, 'error': '商品库存不足'})
        conn.hset(cart_key, sku_id, count)

        total_count = conn.hlen(cart_key)
        return JsonResponse({'res': 5, 'message': '商品数量出错', 'total_count': total_count})


class CartInfoView(LoginRequiredMixin, View):
    def get(self, request):
        # 获取用户购物车信息
        user = request.user
        conn = get_redis_connection('default')
        cart_key = 'cart_%d' % user.id
        cart_dict = conn.hgetall(cart_key)
        skus = []
        total_count = 0
        total_price = 0
        # 遍历获取的商品信息
        for sku_id, count in cart_dict.items():
            sku = GoodsSKU.objects.get(id=sku_id)
            amount = sku.price*int(count)
            sku.count = int(count)
            sku.amount = amount
            total_count += int(count)
            total_price += amount
            skus.append(sku)

        # 组织上下文
        context = {'total_count': total_count,
                   'total_price': total_price, 'skus': skus}
        return render(request, 'cart.html', context)


class CartUpdateView(View):
    def post(self, request):
        sku_id = request.POST.get('sku_id')
        count = request.POST.get('count')
        user = request.user
        if not user.is_authenticated:
            return JsonResponse({'res': 4, 'error': '请登录'})

        if not all([sku_id, count]):
            return JsonResponse({'res': 0, 'error': '数据不完整'})

        try:
            count = int(count)
        except Exception as e:
            return JsonResponse({'res': 1, 'error': '商品数量出错'})

        try:
            sku = GoodsSKU.objects.get(id=sku_id)
        except GoodsSKU.DoesNotExist:
            return JsonResponse({'res': 2, 'error': '商品不存在'})

        if count > sku.stock:
            return JsonResponse({'res': 6, 'error': '商品库存不足'})
        conn = get_redis_connection('default')
        cart_key = 'cart_%d' % user.id
        conn.hset(cart_key, sku_id, count)
        total_count = 0
        vals = conn.hvals(cart_key)
        for val in vals:
            total_count += int(val)

        return JsonResponse({'res': 5, 'message': '更新成功', 'total_count': total_count})


class CartDeleteView(View):
    def post(self, request):
        sku_id = request.POST.get('sku_id')
        user = request.user
        if not user.is_authenticated:
            return JsonResponse({'res': 4, 'error': '请登录'})
        if not sku_id:
            return JsonResponse({'res': 0, 'error': '数据不完整'})
        try:
            sku = GoodsSKU.objects.get(id=sku_id)
        except GoodsSKU.DoesNotExist:
            return JsonResponse({'res': 2, 'error': '商品不存在'})
        conn = get_redis_connection('default')
        cart_key = 'cart_%d' % user.id
        conn.hdel(cart_key, sku_id)
        total_count = 0
        vals = conn.hvals(cart_key)
        for val in vals:
            total_count += int(val)

        return JsonResponse({'res': 3, 'message': '删除成功', 'total_count': total_count})

dailyfresh/templates/base.html
<!DOCTYPE html
    PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
{% load static %}

<head>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css'%}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css'%}">
    <script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>

    {% block topfiles %}{% endblock topfiles %}

</head>

<body>
    <div class="header_con">
        <div class="header">
            <div class="welcome fl">欢迎来到天天生鲜!</div>
            <div class="fr">
                {% if user.is_authenticated %}
                <div class="login_btn fl">
                    欢迎您：<em>{{ user.username }}</em>
                </div>
                {% else %}
                <div class="login_btn fl">
                    <a href="{% url 'user:login' %}">登录</a>
                    <span>|</span>
                    <a href="{% url 'user:register' %}">注册</a>
                </div>
                {% endif %}
                <div class="user_link fl">
                    <span>|</span>
                    <a href="{% url 'user:center' %}">用户中心</a>
                    <span>|</span>
                    <a href="{% url 'cart:show' %}">我的购物车</a>
                    <span>|</span>
                    <a href="{% url 'user:order' 1 %}">我的订单</a>
                </div>
            </div>
        </div>
    </div>
    {% block body %}

    {% endblock body %}
    <div class="footer no-mp">
        <div class="foot_link">
            <a href="#">关于我们</a>
            <span>|</span>
            <a href="#">联系我们</a>
            <span>|</span>
            <a href="#">招聘人才</a>
            <span>|</span>
            <a href="#">友情链接</a>
        </div>
        <p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
        <p>电话：010-****888 京ICP备*******8号</p>
    </div>
</body>

dailyfresh/templates/list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
{{type.name}}
{% endblock title %}
{% block topfiles %}

{% endblock topfiles %}
{% block body %}


<div class="search_bar clearfix">
	<a href="index.html" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
	<div class="search_con fl">
		<form method="GET" action="/search">
			<input type="text" class="input_text fl" name="q" placeholder="搜索商品">
			<input type="submit" class="input_btn fr" name="" value="搜索">
		</form>
	</div>
	<div class="guest_cart fr">
		<a href="#" class="cart_name fl">我的购物车</a>
		<div class="goods_count fl">{{cart_count}}</div>
	</div>
</div>

<div class="navbar_con">
	<div class="navbar clearfix">
		<div class="subnav_con fl">
			<h1>全部商品分类</h1>
			<span></span>
			<ul class="subnav">

				{% for type in types %}
				<li><a href="{% url 'goods:list' type.id 1 %}" class="{{type.logo}}">{{type.name}}</a></li>
				{% endfor %}
			</ul>
		</div>
		<ul class="navlist fl">
			<li><a href="">首页</a></li>
			<li class="interval">|</li>
			<li><a href="">手机生鲜</a></li>
			<li class="interval">|</li>
			<li><a href="">抽奖</a></li>
		</ul>
	</div>
</div>

<div class="breadcrumb">
	<a href="#">全部分类</a>
	<span>></span>
	<a href="#">{{type.name}}</a>
</div>

<div class="main_wrap clearfix">
	<div class="l_wrap fl clearfix">
		<div class="new_goods">
			<h3>新品推荐</h3>
			<ul>

				{% for sku in new_goods  %}
				<li>
					<a href="{% url 'goods:detail' sku.id %}"><img src="{{sku.image.url}}"></a>
					<h4><a href=" {% url 'goods:detail' sku.id %}">{{sku.name}}</a></h4>
					<div class="prize">￥{{sku.price}}</div>
				</li>
				{% endfor %}
			</ul>
		</div>
	</div>

	<div class="r_wrap fr clearfix">
		<div class="sort_bar">
			<a href="{% url 'goods:list' type.id 1 %}" {% if sort == 'default' %} class="active" {% endif %}>默认</a>
			<a href="{% url 'goods:list' type.id 1 %}?sort=price" {% if sort == 'price' %} class="active"
				{% endif %}>价格</a>
			<a href="{% url 'goods:list' type.id 1 %}?sort=hot" {% if sort == 'hot' %} class="active" {% endif %}>人气</a>
		</div>

		<ul class="goods_type_list clearfix">

			{% for sku in skus_page.object_list %}
			<li>
				<a href="{% url 'goods:detail' sku.id %}"><img src="{{sku.image.url}}"></a>
				<h4><a href="{% url 'goods:detail' sku.id %}">{{sku.name}}</a></h4>
				<div class="operate">
					<span class="prize">￥{{sku.price}}</span>
					<span class="unit">{{sku.price}}/{{sku.unite}}</span>
					<a href="#" class="add_goods" title="加入购物车"></a>
				</div>
			</li>
			{% endfor %}



		</ul>

		<div class="pagenation">

			{% if skus_page.has_previous %}
			<a href="{% url 'goods:list' type.id skus_page.previous_page_number %}?sort={{sort}}">上一页</a>
			{% endif %}
			{% for pindex in pages %}
			{% if pindex == skus_page.number %}
			<a href="{% url 'goods:list' type.id pindex %}?sort={{sort}}" class="active">{{pindex}}</a>
			{%else%}
			<a href="{% url 'goods:list' type.id pindex %}?sort={{sort}}">{{pindex}}</a>
			{% endif %}
			{% endfor %}
			{% if skus_page.has_next %}
			<a href="{% url 'goods:list' type.id skus_page.next_page_number %}?sort={{sort}}">下一页</a>
			{% endif %}


		</div>
	</div>
</div>
{% endblock body %}

dailyfresh/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
登录
{% endblock title %}
{% block topfiles %}

{% endblock topfiles %}
{% block body %}
<div class="login_top clearfix">
	<a href="" class="login_logo"><img src="{% static 'images/logo02.png' %} "></a>
</div>

<div class="login_form_bg">
	<div class="login_form_wrap clearfix">
		<div class="login_banner fl"></div>
		<div class="slogan fl">日夜兼程 · 急速送达</div>
		<div class="login_form fr">
			<div class="login_title clearfix">
				<h1>用户登录</h1>
				<a href="#">立即注册</a>
			</div>
			<div class="form_input">
				<form method="POST">
					{% csrf_token %}
					<input type="text" name="username" class="name_input" placeholder="请输入用户名">
					<div class="user_error">输入错误</div>
					<input type="password" name="pwd" class="pass_input" placeholder="请输入密码">
					<div class="pwd_error">输入错误</div>
					<div class="more_input clearfix">
						<input type="checkbox" name="remember">
						<label>记住用户名</label>
						<a href="#">忘记密码</a>
					</div>
					<input type="submit" name="" value="登录" class="input_submit">
				</form>
			</div>
		</div>
	</div>
</div>

{% endblock body %}

dailyfresh/templates/user_center_info.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
天天生鲜-用户中心
{% endblock title %}
{% block topfiles %}

{% endblock topfiles %}
{% block body %}

<div class="search_bar clearfix">
	<a href="{% url 'goods:index' %}" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
	<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;用户中心</div>
	<div class="search_con fr">
		<input type="text" class="input_text fl" name="" placeholder="搜索商品">
		<input type="button" class="input_btn fr" name="" value="搜索">
	</div>
</div>

<div class="main_con clearfix">
	<div class="left_menu_con clearfix">
		<h3>用户中心</h3>
		<ul>
			<li><a href="{% url 'user:center' %}" class="active">· 个人信息</a></li>
			<li><a href="{% url 'user:order' 1 %}">· 全部订单</a></li>
			<li><a href="{% url 'user:address' %}">· 收货地址</a></li>
		</ul>
	</div>
	<div class="right_content clearfix">
		<div class="info_con clearfix">
			<h3 class="common_title2">基本信息</h3>
			<ul class="user_info_list">
				<li><span>用户名：</span>{{user.username}}</li>
				{% if address %}
				<li><span>联系方式：</span>{{address.phone}}</li>
				<li><span>联系地址：</span>{{address.addr}}</li>
				{% endif %}


			</ul>
		</div>

		<h3 class="common_title2">最近浏览</h3>
		<div class="has_view_list">
			<ul class="goods_type_list clearfix">

				{% for goods in goods_list %}
				<li>
					<a href="{% url 'goods:detail' goods.id %}"><img src="{{goods.image.url}}"></a>
					<h4><a href="{% url 'goods:detail' goods.id %}">{{goods.name}}</a></h4>
					<div class="operate">
						<span class="prize">￥{{goods.price}}</span>
						<span class="unit">{{goods.price}}/{{goods.unite}}</span>
						<a href="#" class="add_goods" title="加入购物车"></a>
					</div>
				</li>
				{% endfor %}
			</ul>
		</div>
	</div>
</div>

{% endblock body %}

dailyfresh/templates/user_center_order.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
天天生鲜-我的订单
{% endblock title %}
{% block topfiles %}

{% endblock topfiles %}
{% block body %}

<div class="search_bar clearfix">
	<a href="{% url 'goods:index' %}" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
	<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;用户中心</div>
	<div class="search_con fr">
		<input type="text" class="input_text fl" name="" placeholder="搜索商品">
		<input type="button" class="input_btn fr" name="" value="搜索">
	</div>
</div>

<div class="main_con clearfix">
	<div class="left_menu_con clearfix">
		<h3>用户中心</h3>
		<ul>
			<li><a href="{% url 'user:center' %}">· 个人信息</a></li>
			<li><a href="{% url 'user:order' 1 %}" class="active">· 全部订单</a></li>
			<li><a href="{% url 'user:address' %}">· 收货地址</a></li>
		</ul>
	</div>
	<div class="right_content clearfix">
		<h3 class="common_title2">全部订单</h3>
		{% csrf_token %}
		{% for order in orders_page %}
		<ul class="order_list_th w978 clearfix">
			<li class="col01">{{order.create_time}}</li>
			<li class="col02">订单号：{{order.order_id}}</li>
			<li class="col02 stress">{{order.status_name}}</li>
		</ul>

		<table class="order_list_table w980">
			<tbody>
				<tr>
					<td width="55%">
						{% for order_sku in order.order_skus %}
						<ul class="order_goods_list clearfix">
							<li class="col01"><img src="{{order_sku.sku.image.url}}"></li>
							<li class="col02">
								{{order_sku.sku.name}}<em>{{order_sku.price}}元/{{order_sku.sku.unite}}</em></li>
							<li class="col03">{{order_sku.count}}</li>
							<li class="col04">{{order_sku.amount}}元</li>
						</ul>
						{% endfor %}
					</td>
					<td width="15%">{{order.total_price|add:order.transit_price}}元</td>
					<td width="15%">{{order.status_name}}</td>
					<td width="15%"><a href="#" order_id={{order.order_id}} status={{order.order_status}}
							class="oper_btn">去付款</a></td>
				</tr>
			</tbody>
		</table>
		{% endfor %}

		<div class="pagenation">
			{% if orders_page.has_previous %}
			<a href="{% url 'user:order' orders_page.previous_page_number %}">上一页</a>
			{% endif %}
			{% for pindex in pages %}
			{% if pindex == orders_page.number %}
			<a href="{% url 'user:order' pindex %}" class="active">{{pindex}}</a>
			{%else%}
			<a href="{% url 'user:order' pindex %}">{{pindex}}</a>
			{% endif %}
			{% endfor %}
			{% if orders_page.has_next %}
			<a href="{% url 'user:order' orders_page.next_page_number %}">下一页</a>
			{% endif %}
		</div>
	</div>
</div>
<script>
	$('.oper_btn').click(function () {

		status = $(this).attr('status')
		order_id = $(this).attr('order_id')
		csrf = $('input[name="csrfmiddlewaretoken"]').val()
		params = {
			'order_id': order_id,
			'csrfmiddlewaretoken': csrf
		}
		if (status == 1) {
			$.post('/order/pay', params, function (data) {
				if (data.res == 3) {
					window.open(data.pay_url)
					$.post('/order/check', params, function (data) {
						if (data.res == 3) {
							alert('支付成功')
							location.reload()
						}
					})
				} else {
					alert(data.errmsg)
				}

			})
		} else {

		}

	})
</script>
{% endblock body %}

dailyfresh/templates/user_center_site.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
天天生鲜-收获地址
{% endblock title %}
{% block topfiles %}

{% endblock topfiles %}

{% block body %}

<div class="search_bar clearfix">
	<a href="{% url 'goods:index' %}" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
	<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;用户中心</div>
	<div class="search_con fr">
		<input type="text" class="input_text fl" name="" placeholder="搜索商品">
		<input type="button" class="input_btn fr" name="" value="搜索">
	</div>
</div>

<div class="main_con clearfix">
	<div class="left_menu_con clearfix">
		<h3>用户中心</h3>
		<ul>
			<li><a href="{% url 'user:center' %}">· 个人信息</a></li>
			<li><a href="{% url 'user:order' 1 %}">· 全部订单</a></li>
			<li><a href="{% url 'user:address' %}" class="active">· 收货地址</a></li>
		</ul>
	</div>
	<div class="right_content clearfix">
		<h3 class="common_title2">收货地址</h3>
		<div class="site_con">

			{% if address %}
			<dl>
				<dt>当前地址：</dt>
				<dd>{{ address.addr }}（{{ address.receiver}} 收） {{ address.phone }}</dd>
			</dl>
			{% else %}
			<p>无默认地址</p>
			{% endif %}


		</div>
		<h3 class="common_title2">编辑地址</h3>
		<div class="site_con">
			<form method="POST">
				{% csrf_token %}
				<div class="form_group">
					<label>收件人：</label>
					<input type="text" name="receiver">
				</div>
				<div class="form_group form_group2">
					<label>详细地址：</label>
					<textarea class="site_area" name="addr"></textarea>
				</div>
				<div class="form_group">
					<label>邮编：</label>
					<input type="text" name="zip_code">
				</div>
				<div class="form_group">
					<label>手机：</label>
					<input type="text" name="phone">
				</div>

				<input type="submit" name="" value="提交" class="info_submit">
			</form>
		</div>
	</div>
</div>
{% endblock body %}